name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # IMPORTANT
    steps:
      - uses: actions/checkout@v3

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Dharanish-AM
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || echo "No changes"
          git push